### ISSUE TITLE
sponge init panic

### ISSUE THREAD

**Issue by pokitpeng** [zhufuyi/sponge#10]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is
```go
go version go1.21.0 darwin/arm64
```

2. The error is
```
sponge init
panic: cgroup cpu init failed!err:=not implemented yet

goroutine 1 [running]:
github.com/zhufuyi/sponge/pkg/shield/cpu.init.0()
	/Users/user/go/pkg/mod/github.com/zhufuyi/sponge@v1.5.5/pkg/shield/cpu/stat.go:33 +0xfc

```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**

- OS: [mac os]
- sponge version [1.5.5]

**More description**

**Comment by zhufuyi** [comment]
This error is caused by an error returned by the dependency library [gopsutil](https://github.com/shirou/gopsutil), indicating that gopsutil does not support obtaining information about your CPU, similar to [#8](https://github.com/zhufuyi/sponge/issues/8).

**Comment by pokitpeng** [comment]
Thank you very much, it works to me.
