### ISSUE TITLE
期望把框架/示例/贡献组件分成三个库来维护

### ISSUE THREAD

**Issue by reatang** [zhufuyi/sponge#2]
做分层可以让使用更加灵活

**Comment by zhufuyi** [comment]
你说的这样分开维护也考虑过，觉得还是把框架本身做成是一个标准化的示例(模板代码)，对于生成代码会更友好一点，生成的服务代码和框架代码是同一套代码，对于使用者也更容易掌握，看懂了生成的服务代码，也就看懂了整个框架。
可以把sponge目录当作是框架目录，把pkg目录当作组件目录，把examples目录当作存放依赖框架和组件的示例目录
