### ISSUE TITLE
集成组件更新

### ISSUE THREAD

**Issue by chenjink674** [zhufuyi/sponge#21]
sponge是一个很优秀的开发框架，提供了多种内置组件和快速开发方式。不过内置的组件较多来带的问题是：如果涉及到内置组件，比如gin或Consul的版本更新，请问这种组件更新一般如何处理比较好？如果直接使用更新组件版本是否会影响sponge框架逻辑？

**Comment by zhufuyi** [comment]
更新组件版本须注意新版本和旧组件版本是否兼容，要测试才知道，如果版本不兼容，但又必须更新组件版本，那就需要在生成的服务代码中使用你自己实现版本的组件替换sponge的组件。
