### ISSUE TITLE
sponge init 失败

### ISSUE THREAD

**Issue by jianhao84** [zhufuyi/sponge#23]
$ sponge init
initialize sponge ......
❌ upgrade sponge binary.
Error: go: github.com/zhufuyi/sponge/cmd/sponge@latest: module github.com/zhufuyi/sponge/cmd/sponge: Get "https://proxy.golang.org/github.com/zhufuyi/sponge/cmd/sponge/@v/list": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by zhufuyi** [comment]
网络问题，科学上网或设置国内代理来解决。
