### ISSUE TITLE
使用postgres数据库床建一个项目失败

### ISSUE THREAD

**Issue by nekorrrr** [zhufuyi/sponge#25]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go

   ```
2. The error is
有可能是数据库字段类型的错误？

**Expected behavior**

**Screenshots**
![image](https://github.com/zhufuyi/sponge/assets/45645775/665529a4-e5ad-47c3-84da-6d0c47276a18)
![image](https://github.com/zhufuyi/sponge/assets/45645775/0aeb114f-f6ca-403c-97b4-263840823883)

**Environments (please complete the following information):**

- OS: windows
- sponge version v1.6.2

**More description**
如图所示

**Comment by zhufuyi** [comment]
这是在postgresql创建的表

```sql
create table users
(
    id          bigint not null,
    user_id character varying(50) not null,
    user_name character varying(100)
);
```

用这个表可以生成代码，没有出现错误，你导出sql看看是什么样的。

**Comment by nekorrrr** [comment]
> 这是在postgresql创建的表
> 
> ```sql
> create table users
> (
>     id          bigint not null,
>     user_id character varying(50) not null,
>     user_name character varying(100)
> );
> ```
> 
> 用这个表可以生成代码，没有出现错误，你导出sql看看是什么样的。

-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL,
    user_id character varying COLLATE pg_catalog."default" NOT NULL,
    user_name character varying COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id, user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

这是用pgadmin导出的DDL

**Comment by zhufuyi** [comment]
这个bug在 `v1.6.3` 版本已修复，可以执行 `sponge upgrade` 升级到最新版本。

**Comment by nekorrrr** [comment]
> 这个bug在 `v1.6.3` 版本已修复，可以执行 `sponge upgrade` 升级到最新版本。

经测试问题已经解决，感谢您的回答！
