### ISSUE TITLE
如何使用goland运行和Debug生成出来的项目

### ISSUE THREAD

**Issue by nekorrrr** [zhufuyi/sponge#26]
**Is your feature request related to a problem? Please describe.**
刚刚接触到go语言，想了解一下如何在goland中运行和debug生成出来的项目，目前配置好会报grep错误，我猜测可能是goland默认终端使用的是cmd，而不是cmder。

**Describe the solution you'd like**
我想在goland中直接运行生产出来的项目
目前我的配置
![image](https://github.com/zhufuyi/sponge/assets/45645775/6cd5e0ce-c206-49e4-8a65-677380650720)
运行时报的错
![image](https://github.com/zhufuyi/sponge/assets/45645775/612cec92-8c96-4af8-b9dd-a61ce35a283e)

**Comment by zhufuyi** [comment]
可以在linux、macOS可以在goland下的默认终端，windows下的goland默认终端cmd无法执行一些依赖的linux命令，你可以设置goland默认终端为cmder。

**Comment by nekorrrr** [comment]
> 可以在linux、macOS可以在goland下的默认终端，windows下的goland默认终端cmd无法执行一些依赖的linux命令，你可以设置goland默认终端为cmder。

设置完默认终端了，但是运行时还是会用Windows的默认终端。。很神奇

**Comment by nekorrrr** [comment]
> 可以在linux、macOS可以在goland下的默认终端，windows下的goland默认终端cmd无法执行一些依赖的linux命令，你可以设置goland默认终端为cmder。

目前看来goland无法设置启动配置的默认终端，这就导致脚本会报错，当然在cmder中输入make run可以正常启动，但是debug又成为了另一个问题。在windows上开发目前看来并不理想，环境配置方面比较麻烦。还是希望可以为windows多做一些适配。

**Comment by nekorrrr** [comment]
> 可以在linux、macOS可以在goland下的默认终端，windows下的goland默认终端cmd无法执行一些依赖的linux命令，你可以设置goland默认终端为cmder。

或者说我在cmder使用make run启动服务，然后有没有方法在goland中进行断点Debug

**Comment by nekorrrr** [comment]
> 可以在linux、macOS可以在goland下的默认终端，windows下的goland默认终端cmd无法执行一些依赖的linux命令，你可以设置goland默认终端为cmder。

通过设置windows环境变量解决了这个问题，现在可以通过goland的Run Configution中运行了，但是现在有了另一个问题，我该如何使用goland进行断点debug呢？

添加windows环境变量：C:\Program Files\Git\bin 
这样他就会去找sh了，相比cmd他好像更优先使用sh

**Comment by zhufuyi** [comment]
运行服务不一定需要make run命令，用goland打开项目代码，在cmd/项目名称/main.go文件，可以执行断点debug的。

**Comment by nekorrrr** [comment]
> 运行服务不一定需要make run命令，用goland打开项目代码，在cmd/项目名称/main.go文件，可以执行断点debug的。

感谢，也就是说不一定非要用make run去运行服务，正常从main函数运行也是跟make run的方法是一样的，make docs不需要每次都执行，而是只有接口的增删改才需要去执行。

感谢您的回答，问题已经解决！
