### ISSUE TITLE
有一个小疑问。。

### ISSUE THREAD

**Issue by nekorrrr** [zhufuyi/sponge#28]
在视频中我看到比方说有三个rpc服务，一个网关服务，然后通过网关服务去调用rpc服务。
如果我有这样一个需求，我不需要网关服务，我有一个protobuff生成的web服务，里面都是暴露给前台的接口，这个时候我其中一个接口想调用一个rpc服务，这个可以通过代码自动生成去实现么？

如果可以的话还有一个问题，比方说名称相同的情况，web服务有一个叫user.proto文件而rpc服务中也有一个叫user.proto的文件，当然，如果两个服务都是同一个项目组去做可以通过命名的方式去做区分，但是也有可能是两个不同的项目组，这样同名的情况应该怎么办？

**Comment by zhufuyi** [comment]
第一个问题，可以的，在web服务调用一个grpc服务，可以参考这里的[文档](https://go-sponge.com/zh-cn/rpc-gateway-development-protobuf?id=%f0%9f%8f%b7%e5%af%b9%e6%8e%a5grpc%e6%9c%8d%e5%8a%a1%e7%9b%b8%e5%85%b3%e6%93%8d%e4%bd%9c)

第二个问题，要注意的是配置服务名称(服务注册与发现)建议由项目名+服务名组成。其实根据一个proto文件可以生成一个服务代码同时提供http和grpc两种类型api，这个功能没有开源出来。

**Comment by nekorrrr** [comment]
> 第一个问题，可以的，在web服务调用一个grpc服务，可以参考这里的[文档](https://go-sponge.com/zh-cn/rpc-gateway-development-protobuf?id=%f0%9f%8f%b7%e5%af%b9%e6%8e%a5grpc%e6%9c%8d%e5%8a%a1%e7%9b%b8%e5%85%b3%e6%93%8d%e4%bd%9c)
> 
> 第二个问题，要注意的是配置服务名称(服务注册与发现)建议由项目名+服务名组成。其实根据一个proto文件可以生成一个服务代码同时提供http和grpc两种类型api，这个功能没有开源出来。

可以做一个web服务调用grpc服务的example么？如果可以的话非常感谢！
