### ISSUE TITLE
生成文档时swag会报错

### ISSUE THREAD

**Issue by lirixiang** [zhufuyi/sponge#29]
**Describe the bug**
生成文档时swag会报错

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
// @title ChatGPT_MJ_aggregation_next api docs
// @description http server api docs
// @schemes http https
// @version 2.0
// @host localhost:8080
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description "Type Bearer your-jwt-token" to Value
func main() {
	initial.InitApp()
	services := initial.CreateServices()
	closes := initial.Close(services)

	a := app.New(services, closes)
	a.Run()
}

   ```
2. The error is

   ```
// @description "Type Bearer your-jwt-token" to Value

   ```
3.将// @description "Type Bearer your-jwt-token" to Value 改成
// @description Type Bearer your-jwt-token to Value  可以解决

**Comment by zhufuyi** [comment]
生成代码是下面这样，没有报错

```go
// @description Type Bearer "your-jwt-token" to Value
```

是不是你手动改为下面这样导致swag报的错误呢

```go
// @description "Type Bearer your-jwt-token" to Value
```

**Comment by lirixiang** [comment]
<img width="1310" alt="image" src="https://github.com/zhufuyi/sponge/assets/51286783/cd3fcd3f-d266-4e4d-86cf-05ea449f89e2">
<img width="601" alt="image" src="https://github.com/zhufuyi/sponge/assets/51286783/c4623355-2dbc-4c7d-9ad6-0a8a0d4fb8cd">
用浏览器抓取了一下，是会报错

**Comment by zhufuyi** [comment]
我用的swag版本是v1.8.12，生成swagger文档时，`"`会被转义`\"`，因此不会报错。
