### ISSUE TITLE
扩展下，基于数据库和多个文件生成代码多好，现在的单个表和文件还是太薄弱了些

### ISSUE THREAD

**Issue by jibenliu** [zhufuyi/sponge#3]

**Comment by zhufuyi** [comment]
**有些功能代码，使用命令来生成会更加省事，特别是在一个服务上添加handler、service、dao、model、rpcclient、rpc-cli这些功能代码，只需要通过--out参数指定服务目录，生成的代码自动融入到服务代码中，可以查看使用s`-h`来查看使用示例，并且都支持多表或多文件。**


1 支持多表生成代码功能的，UI界面暂时还没弄上去

web类型，基于t1,t2两个mysql表handler代码命令
> sponge web handler --module-name=yourModuleName --db-dsn=root:123456@(192.168.3.37:3306)/test --db-table=t1,t2

rpc类型，基于t1,t2两个mysql表service代码命令
> sponge micro service --module-name=yourModuleName --server-name=yourServerName --db-dsn=root:123456@(192.168.3.37:3306)/test --db-table=t1,t2

生成dao、model命令也是类似的，在--db-table参数后面填写多个表，用逗号分隔即可

2 多文件(例如yaml、protobuf)生成代码，UI界面已经支持，在UI界面选择多个文件即可

**Comment by zhufuyi** [comment]
**有些功能代码，使用命令来生成会更加省事，特别是在一个服务上添加handler、service、dao、model、rpcclient、rpc-cli这些功能代码，只需要通过--out参数指定服务目录，生成的代码自动融入到服务代码中，可以查看使用s`-h`来查看使用示例，并且都支持多表或多文件。**


1 支持多表生成代码功能的，UI界面暂时还没弄上去

web类型，基于t1,t2两个mysql表handler代码命令
> sponge web handler --module-name=yourModuleName --db-dsn=root:123456@(192.168.3.37:3306)/test --db-table=t1,t2

rpc类型，基于t1,t2两个mysql表service代码命令
> sponge micro service --module-name=yourModuleName --server-name=yourServerName --db-dsn=root:123456@(192.168.3.37:3306)/test --db-table=t1,t2

生成dao、model命令也是类似的，在--db-table参数后面填写多个表，用逗号分隔即可

2 多文件(例如yaml、protobuf)生成代码，UI界面已经支持，在UI界面选择多个文件即可
