### ISSUE TITLE
基于sql创建web报错, 

### ISSUE THREAD

**Issue by longfei347** [zhufuyi/sponge#33]
填写表单,后点 下载代码 报错

The error is

  Internal Server Error, exec: "sponge": cannot run executable found relative to current directory

**Comment by longfei347** [comment]
原来是要 将 {user}\go\bin 加到path里,  前期准备没说清楚;

**Comment by longfei347** [comment]
另外对window用户太不友好, 安装时,要可用linux命令, 可以装一个git, 通过git bash来运行sponge init
另外的make docs,  make run  就没法执行了, 需要根据 makefile里执行步骤进行相应的window上操作, 其实就是go的安装运行
文档里也不说清楚点...

**Comment by longfei347** [comment]
现在编程辅助工具插件那么多, 这种crud的操作, 基本都能自动生成, 有点鸡肋, 不如多试下那些插件 chatmoss, codeGeex, 通义灵码, kimi, openai, 360智能助手 ...

**Comment by zhufuyi** [comment]
在windows环境支持两种安装方式：

- [快捷安装文档](https://github.com/zhufuyi/sponge/blob/main/assets/install-cn.md#windows%E7%8E%AF%E5%A2%83)
- [原生安装文档](https://go-sponge.com/zh-cn/quick-start?id=%e5%ae%89%e8%a3%85-sponge)

sponge.exe安装在$GOBIN目录下，不要在$GOBIN目录执行`sponge run`命令启动ui界面服务，否则生成代码时会报相对路径错误，但可以在$GOBIN目录执行sponge命令行方式来生成代码。

我也常使用AI辅助编程工具(chatGPT 4、claude 3、fitten code, codeium等)，只是用来生成某些功能片段代码，不少生成的代码还要经过人工调整才能使用，这样也可以提高一些编程效率，但不要过于神话AI辅助编程工具。例如让AI辅助工具 `基于mysql的user表生成go语言的CRUD代码，要求使用gin和gorm框架，要求CRUD代码支持自定义条件查询，支持分页、支持缓存(防击穿、防穿透)、支持swagger文档等`，试过多种AI辅助工具生成的CRUD代码没有一个能满足实际项目要求的。
