### ISSUE TITLE
logger WithFields 打印caller不对

### ISSUE THREAD

**Issue by BianZLL** [zhufuyi/sponge#39]
![image](https://github.com/zhufuyi/sponge/assets/45144990/5ebd745c-9ee6-4a9a-b5d7-98715615b8e0)

![image](https://github.com/zhufuyi/sponge/assets/45144990/99e8fdc5-f60c-4fdb-8d5f-dfa1b8f5f278)
加上WithFields之后，打印到了调用处行数。

**Comment by zhufuyi** [comment]
已修复，是WithFields的AddCallerSkip问题，下个版本生效。
