### ISSUE TITLE
表明是mysql 关键字生成代码会异常

### ISSUE THREAD

**Issue by yuanliubei** [zhufuyi/sponge#40]
![image](https://github.com/zhufuyi/sponge/assets/27850130/1dc2233f-b1e7-4b20-8df2-5ef45796c2fa)
![image](https://github.com/zhufuyi/sponge/assets/27850130/2aae4033-e462-4a17-b374-bcc8eb2d2cd8)

可以优化一下

**Comment by zhufuyi** [comment]
方便展示完整的order表吗，通过你提供的错误信息无法判断sql语法错误的原因。

**Comment by yuanliubei** [comment]
CREATE TABLE `order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `product_id` bigint(20) NOT NULL,
  `product_title` varchar(128) NOT NULL,
  `product_price` decimal(10,2) NOT NULL,
  `amount` int(11) DEFAULT NULL,
  `total_price` decimal(10,2) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by yuanliubei** [comment]
表名是`order`，所以报错。

**Comment by zhufuyi** [comment]
这是表名与mysql关键字同名产生的问题，已经修复了，要在下一个版本才生效。

**Comment by yuanliubei** [comment]
tks
