### ISSUE TITLE
Please translate the web UI to english

### ISSUE THREAD

**Issue by lpintes** [zhufuyi/sponge#42]
The UI is currently unusable for international community.
Would it be so difficult to translate it?

**Comment by zhufuyi** [comment]
You can switch to English in the upper right corner.

<br>

![image](https://github.com/zhufuyi/sponge/assets/14330269/6d286c06-1b87-4ede-812e-ffd0d66b1a64)

**Comment by lpintes** [comment]
Sorry, this didn't seem to be relevant but I am using a screen reader. So I am unable to "see" anything relevant that would allow me to switch the language.
