### ISSUE TITLE
Time.Now 数据库字段datetime

### ISSUE THREAD

**Issue by wangjintianya** [zhufuyi/sponge#46]
**Describe the bug**
Time.Now 数据库字段datetime ,在dao结构体中gorm是指针，但是test文件里面是给的不是地址

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go

   ```
2. The error is

   ```

   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**

- OS: [e.g. Linux]
- sponge version [e.g. 1.1.1]

**More description**

**Comment by zhufuyi** [comment]
用来生成代码的表可能没有created_at和updated_at列，下个sponge版本生成dao test代码会把赋值给CreatedAt和UpdatedAt这两行代码将会注释掉。
