### ISSUE TITLE
如何直接返回validate的信息呢,如果要把每个validate都定义ecode有点费劲

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#47]
如何直接返回validate的信息呢,如果要把每个validate都定义ecode有点费劲

**Comment by hanwenbo** [comment]
c.JSON(http.StatusOK, gin.H{"code": ecode.InvalidParams.Code(), "msg": err.Error()})
假如这样 会返回以下json ,有没有什么办法 让其只返回某个字段的错误 不是全部错误 , 还有就是要支持多语言
```
{
    "code": 10001,
    "msg": "Key: 'CreateRequest.EventProperties' Error:Field validation for 'EventProperties' failed on the 'json' tag"
}
```

**Comment by zhufuyi** [comment]
http和grpc的api的validate有对应的错误码，不需要定义，默认不返回错误原因信息，如果想返回validate具体信息，需要手动额外加进去例如：

http服务
> response.Error(c, ecode.InvalidParams, err.Error())

grpc服务
> return nil, ecode.StatusInvalidParams.Err(ecode.Any("err", err.Error()))

错误信息由validate库返回，具体是否要加工validate错误信息需要使用者处理。

**Comment by hanwenbo** [comment]
收到 谢谢
