### ISSUE TITLE
请问 response里有一些敏感的信息 如何在log里隐藏呢

### ISSUE THREAD

**Issue by lijianow** [zhufuyi/sponge#55]
比如登录接口，返回的密钥信息会记录在日志里，为了安全我想能不能配置什么过滤掉？

**Comment by lijianow** [comment]
<img width="912" alt="image" src="https://github.com/user-attachments/assets/d805563b-ece9-42b6-a22e-a574f69893a3">
好像作者还没有实现这块的代码

**Comment by zhufuyi** [comment]
在这里可以填写指定路由，表示忽略打印信息，也就不会包含敏感信息的日志了

![image](https://github.com/user-attachments/assets/4f33a3a0-3456-46dd-bbb9-6f957ef6882d)

**Comment by lijianow** [comment]
感谢 收到
