### ISSUE TITLE
windows 下 make proto 报错 protoc: command not found

### ISSUE THREAD

**Issue by Rellopn** [zhufuyi/sponge#6]
系统win11,[根据proto文件创建rpc服务](https://go-sponge.com/zh-cn/create-rpc?id=%e6%a0%b9%e6%8d%aeproto%e6%96%87%e4%bb%b6%e5%88%9b%e5%bb%barpc%e6%9c%8d%e5%8a%a1)已生成好文件。进入生成的目录下执行make proto 报错 protoc: command not found.
![195f8bf44c6e412aa30b42365dd47c3](https://github.com/zhufuyi/sponge/assets/17350150/3706fd97-160c-44be-a37f-7bd384b7e2df)
实际上已经安装了protoc的
![7caa0161995d515f0790b63067b526d](https://github.com/zhufuyi/sponge/assets/17350150/3975385a-2613-4c6f-8568-2e7728c61b2f)
![微信截图_20230616150354](https://github.com/zhufuyi/sponge/assets/17350150/53497b4b-34d6-487b-b04d-203f178a300c)

**Comment by zhufuyi** [comment]
我也是win11系统，我的protoc.exe文件放在和其他插件同一个目录(例如D:\golang\package\bin)，执行`make proto`命令时可以正常调用protoc。

执行命令`where protoc`可以查看protoc的绝对路径，绝对路径尽量不要包含非英文字符(例如空格)。
