### ISSUE TITLE
请问cron的log如何去掉  按秒跑 打印的太多了 控制台调试不好找其他内容

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#62]
https://github.com/zhufuyi/sponge/blob/144e71b4c360585032effec055fcea72828bd55f/pkg/gocron/cron.go#L39

我看这里默认加了withLog  但不知道怎么去掉

**Comment by zhufuyi** [comment]
下个版本添加一个开关控制是否打印INFO，默认是打印的，初始化示例如下：

```
gocron.Init(
	gocron.WithLogger(logger.Get(), true), // true表示设置忽略打印INFO信息
)
```

**Comment by hanwenbo** [comment]
@zhufuyi 最新版本支持了不  我看代码好像是没有
