### ISSUE TITLE
sponge 如何进行单元测试，或者说一些项目脚本如何写，比如php的 cli模式能执行一些脚本，不需要请求web http的接口

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#67]
目前遇到的问题是如果我初始化项目的cmd/app/initial的InitApp就报错，提示没有close ，我想知道作者平时写项目需要一些修复数据的脚本需要如何解决，配置文件要和项目的配置文件一样  不要单独写的那种

我目前的写法是，这我感觉这与sponge项目写的有点脱离，显得乱
<img width="689" alt="image" src="https://github.com/user-attachments/assets/17383996-2451-4a84-8057-c3e4b25b9b19">

**Comment by zhufuyi** [comment]
- 配置文件对应的go结构体对应在`internal/config/服务名.go`，可以从这里获取配置，如果在yaml有自定义配置，执行`make update-config`更新。
- sponge创建的服务初始化在`cmd/服务名/initial/initApp.go`下，可以把启动服务时修复数据的功能代码在这里执行。

**Comment by hanwenbo** [comment]
make update-config 这个不错 试了一下


sponge创建的服务初始化在cmd/服务名/initial/initApp.go下，可以把启动服务时修复数据的功能代码在这里执行。
————————————————————————————
这个不太方便，因为修复数据可能是多次的
我挺希望是类似你这个命令
make goods update

我目前在试试  Cobra  是否可以满足，在Cobra里面引入 initApp.go里的所有内容（除了启动http server）
