### ISSUE TITLE
请问sponge自带的mysql和mgo 在用户访问量少的时候会断开重连吗

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#72]
守护进程模式 mysql和mgo 会自动重新连接吗，因为我最近发现用户访问少的时候 突然访问一下 mgo会查询失败 我目前猜测是长时间没操作 断开了 遇到过几次

**Comment by zhufuyi** [comment]
在`mongodb服务重启`或`网络断开后恢复`之后都可以正常访问api获取到mongodb数据的。查询mongodb失败有日志记录的，可以从日志看查询失败原因。

**Comment by hanwenbo** [comment]
排查到了  确实mgo会断开 不是长链接，我需要琢磨下怎么保持长连接

**Comment by hanwenbo** [comment]
我在model加了一个 CheckAndReconnect  测试一段时间 没问题的话我再反馈

**Comment by zhufuyi** [comment]
可以设置连接池来保持连接的活跃，示例：

```go
    // case 1: 在dsn设置连接池
    db, err := mgo.Init("mongodb://root:123456@192.168.3.37:27017/account?socketTimeoutMS=30000&maxPoolSize=100&minPoolSize=1&maxConnIdleTimeMS=300000")

    // 或者 在代码设置连接池
    // import "go.mongodb.org/mongo-driver/mongo/options"
    db, err := mgo.Init("mongodb://root:123456@192.168.3.37:27017/account",
        options.Client().SetMaxPoolSize(100),
        options.Client().SetMinPoolSize(1),
        options.Client().SetMaxConnIdleTime(10*time.Minute),
        options.Client().SetSocketTimeout(30*time.Second),
    )
```

**Comment by hanwenbo** [comment]
和maxConnIdleTimeMS应该没关系 因为mongo-driver默认是0  无限使用，我还在排查

**Comment by hanwenbo** [comment]
上面的方法法测试了 会断开  我查了一些资料 https://stackoverflow.com/questions/68945837/updateone-fails-on-client-due-to-timeout-but-mongodb-processes-it-anyway/68946337#68946337   老问题了

目前还在观察其他写法   暂时没想好到好的办法测试 只能是每天观察一下日志  每天都会断开   换了一种写法 还在看

**Comment by hanwenbo** [comment]
升级了最新的mongo-driver  2天内没再复现   看来是mongo-driver的bug。
