### ISSUE TITLE
updateDataByID 这个方法 保存int 为0错误

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#81]
```
if table.OutStockType!= 0 {
		update["out_stock_type"] = table.OutStockType
	}
	
	if table.Name!= "" {
		update["name"] = table.Name
	}

```

如果字段存在有的值该怎么办？
比如 0代表关闭 1代表开启  
name 是名字  名字可能想清空  清空就走 nickname这种  这里j加了!= "" 就会永远保存不了
或者我架构问题  或者思考方式问题， 希望作者能指点下    总之这里作者的用意我没能理解

**Comment by zhufuyi** [comment]
需要手动把该字段定义为指针类型，才能判断出来是否修改为go的默认值。
在model的定义表的字段没有定义为指针原因是：在handler或service尽可能使用copier.Copy批量复制字段值，不需要手动复制，因此定义字段时建议尽可能避开go默认值。

**Comment by hanwenbo** [comment]
好的 理解您的用意了，假如我不怕麻烦  只要是修改我就先获得详情  与  update 提交的部分字段 进行合并覆盖  是不是也没问题？我问一下是担心自己改后 以后不能平滑的升级sponge

我现在的想法就是把updateDataByID里的 update := map[string]interface{}{} 去掉  直接保存 table *xxx.Model ,我要注意的就是 再保存之前已经要先合并原有和新修改的内容 ，不然缺少的修改字段会被改为空

请问我这样操作有问题不？

我希望能保留大量sponge的思路 ，结合部分自己习惯的代码逻辑来实现

**Comment by zhufuyi** [comment]
其实不需要再次获取详情，把字段类型修改为指针后，只需判断传过来的字段是否为nil就知道是否需要修改。

**Comment by hanwenbo** [comment]
指针的话   对内存的消耗大吗？ 我看你很少用指针  我担心我理解的不到位，假如我把批量生成的mysql字段都加指针  保存的时候判断nil确实可以， 主要你没这么干 我有一些担心是不是我思考的不对

**Comment by hanwenbo** [comment]
或者我在想  能不能正则批量把生成的updateDataByID(ctx context.Context, db *gorm.DB, table *orderModuleModel.XXXX)
批量替换为   updateDataByID(ctx context.Context, db *gorm.DB,  map[string]interface{} ) 

这样我保存的时候比较自由    也不需要考虑内存的消耗了？

**Comment by hanwenbo** [comment]
这些问题都原因来自    我的订单状态可以默认为0 订单备注可以为空字符串，但是修改订单状态的时候  大量情况都只是改变一个字段，update现在传入需要为Model 这样就比较难  在我update都时候  假如订单状态某个值变了  我先获取再保存 会有bug产生

**Comment by hanwenbo** [comment]
还有一种办法就是在updateDataByID方法里 加个参数，.Select("xxxx")  默认未 .Select("*")

**Comment by hanwenbo** [comment]
想了挺多  最后决定用这种方法  没你的默认性能高  对我来说用起来要方便一些
```

func Update(ctx context.Context, db *gorm.DB, model interface{}, where map[string]interface{}, data interface{}) (uint64, error) {
	if where == nil || data == nil {
		return 0, errors.New("where and data parameters cannot be nil")
	}

	// Convert struct to map[string]interface{}
	dataValue := reflect.ValueOf(data).Elem()
	dataType := dataValue.Type()
	dataMap := make(map[string]interface{})

	modelValue := reflect.ValueOf(model).Elem()
	modelType := modelValue.Type()

	var id uint64
	var idColumnName string
	for i := 0; i < dataType.NumField(); i++ {
		field := dataType.Field(i)
		tag := field.Tag.Get("gorm")
		tagParts := strings.Split(tag, ";")
		var columnName string
		for _, part := range tagParts {
			if strings.HasPrefix(part, "column:") {
				columnName = strings.TrimPrefix(part, "column:")
				break
			}
		}
		if columnName == "" {
			columnName = field.Name
		}

		// Check if the field exists in the model
		if _, ok := modelType.FieldByName(field.Name); !ok {
			return 0, errors.New("field " + field.Name + " does not exist in the model")
		}

		// Extract id if it exists
		if field.Name == "ID" {
			id = dataValue.Field(i).Uint()
			idColumnName = columnName
			continue
		}

		dataMap[columnName] = dataValue.Field(i).Interface()
	}

	// Add id to where clause if it exists
	if id != 0 {
		where[idColumnName] = id
	}

	return id, db.WithContext(ctx).Model(model).Where(where).Updates(dataMap).Error
}
```
