### ISSUE TITLE
update-config  希望能支持更多

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#85]
update-config:
	@sponge config --server-dir=. --client-dir=internal/config --client-file=config.go
	
	
希望额外支持指定 --client-dir=internal/config --client-file=config.go
	
这是因为我项目的模块很多，我为了分开目录 对路径有调整  config的层级就变了  ，那么我这时候再用make update-config就报错了

**Comment by zhufuyi** [comment]
可以使用命令 `sponge config --yaml-file=file.yml --out=serverDir`

**Comment by hanwenbo** [comment]
--yaml-file=file.yml  挺好 试了 
不过--out=xxxDir 会额外加一层internal/config   我实际路径不是这样
