### ISSUE TITLE
关于空缓存处理的探讨

### ISSUE THREAD

**Issue by dej4vu** [zhufuyi/sponge#87]
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/fbfa01bf-b919-4da6-98a6-dbb69870617d">

框架已经缓存了空记录，但是当检查到缓存记录是空记录时，依然穿透到数据库查询，请问是基于哪些考量？

**Comment by zhufuyi** [comment]
根据id查询，会先去缓存获取，如果从缓存获取成功，直接返回，如果从缓存获取失败，失败原因：

- key不存在
- key存在， 但值为占位符*
- 解码错误

对于key不存在的错误，就会去数据库查询，如果从数据库获取成功，则设置缓存，如果从数据库获取不到记录，设置缓存占位符*。
对于key的值为占位符的错误，直接返回记录不存在；
