### ISSUE TITLE
大佬能做成类似gin vue admin 内种 带页面的吗，快速开发脚手架

### ISSUE THREAD

**Issue by RestartZero** [zhufuyi/sponge#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhufuyi** [comment]
还没有这样的计划，你可以使用 [vue-vben-admin](https://github.com/vbenjs/vue-vben-admin) [vue-vben-admin](https://github.com/vbenjs/vue-vben-admin) 等后台前端解决方案
