### ISSUE TITLE
关于缓存

### ISSUE THREAD

**Issue by hanwenbo** [zhufuyi/sponge#91]
我在想如果是多服务的时候，修改数据库并不是一个单应用控制，那么缓存就存在拉到不是最新的数据的问题。

这种情况的话用sponge的cache是不是就没办法解决了，需要单独起个什么服务 来实时管理缓存？我记得作者之前写过DTM，DTM里有cache能解决类似的问题，目前想了解sponge内部是否有遇到过这个问题  是否有解决。

**Comment by zhufuyi** [comment]
sponge内置的redis作为缓存的实现策略是先删除缓存，读取时再更新缓存，由于网络的延时有可能会导致第一个请求最后更新缓存(虽然存在，但概率非常低)，导致缓存与数据库不是最新版本，但做了5分钟缓存有效时间作为兜底。如果想保证缓存与数据库数据强一致，可以使用DTM来实现，但会有一定性能损耗。

**Comment by hanwenbo** [comment]
谢谢  了解啦 👍    这俩我都试试  目前cache没敢真正用 因为update的model我改为了interface 为了方便存任意字段
